In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [ ]:
col_names=["sepallength","sepalwidth","petallength","petalwidth","class"]
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
dataset=pd.read_csv(url,names=col_names)

In [ ]:
dataset

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
dataset=data.values[:,0:4]
lables=data.values[:,-1]

In [ ]:
dataset

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
import math
def distance(x1,x2):
  distances=0.0
  for i in range(len(x1)):
    distances+=(x1[i]-x2[i])**2
  return(math.sqrt(distances))

In [ ]:
testing_data=data.values[69,0:4]


In [ ]:
distance_cumm=[]
for i in range(len(dataset)):
  distance_cumm.append([distance(dataset,testing_data)])

IndexError: index 4 is out of bounds for axis 0 with size 4

In [ ]:
distance_cumm

[array([10.538026380684384, 8.605230967266365, 21.60694332847661,
        9.393614852653897], dtype=object),
 array([10.538026380684384, 8.605230967266365, 21.60694332847661,
        9.393614852653897], dtype=object),
 array([10.538026380684384, 8.605230967266365, 21.60694332847661,
        9.393614852653897], dtype=object),
 array([10.538026380684384, 8.605230967266365, 21.60694332847661,
        9.393614852653897], dtype=object),
 array([10.538026380684384, 8.605230967266365, 21.60694332847661,
        9.393614852653897], dtype=object),
 array([10.538026380684384, 8.605230967266365, 21.60694332847661,
        9.393614852653897], dtype=object),
 array([10.538026380684384, 8.605230967266365, 21.60694332847661,
        9.393614852653897], dtype=object),
 array([10.538026380684384, 8.605230967266365, 21.60694332847661,
        9.393614852653897], dtype=object),
 array([10.538026380684384, 8.605230967266365, 21.60694332847661,
        9.393614852653897], dtype=object),
 array([10.53802638